### ISSUE TITLE
Templates as OPTs

### ISSUE THREAD

**Issue by jakesmolka** [openehr-nl/ZIBs-on-openEHR#18]
Would it be possible to provide the Templates as OPTs, too? Currently, you have on WebTemplate JSON files available in this repo (https://github.com/openehr-nl/ZIBs-on-openEHR/tree/master/data/web_templates).
I'm hoping you got the modeling information of the Templates stored in some modeling tool and only would need to export to the OPT format.

**Comment by joostholslag** [comment]
Hi Jake, I support the issue. We edit the artefacts in this repo in archetype designer. Will you be able to connect your account on that tool to this repo and make a PR to add the OPTs? Send me an email if you need help.

**Comment by jakesmolka** [comment]
Thanks Joost. Personally, I don’t have this requirement anymore and will close this issue. Sorry for the delay.
